// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq3za5MGHvW4x_1YKBPBCSNWlWr098lRc',
    appId: '1:117621637260:android:6d74ba1b30ba7ec38bfba9',
    messagingSenderId: '117621637260',
    projectId: 'diplomgrinenko',
    storageBucket: 'diplomgrinenko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmRx9am2trm7PSS3Yu8Gzi7fjXzq_hYYU',
    appId: '1:117621637260:ios:bf2165828abe57ee8bfba9',
    messagingSenderId: '117621637260',
    projectId: 'diplomgrinenko',
    storageBucket: 'diplomgrinenko.firebasestorage.app',
    iosBundleId: 'com.diplom.diplomgrinenko',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKiulophvY08WdJxQX31nYq1sgDEHFa7k',
    appId: '1:117621637260:web:5a614139143bc2fb8bfba9',
    messagingSenderId: '117621637260',
    projectId: 'diplomgrinenko',
    authDomain: 'diplomgrinenko.firebaseapp.com',
    storageBucket: 'diplomgrinenko.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmRx9am2trm7PSS3Yu8Gzi7fjXzq_hYYU',
    appId: '1:117621637260:ios:bf2165828abe57ee8bfba9',
    messagingSenderId: '117621637260',
    projectId: 'diplomgrinenko',
    storageBucket: 'diplomgrinenko.firebasestorage.app',
    iosBundleId: 'com.diplom.diplomgrinenko',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKiulophvY08WdJxQX31nYq1sgDEHFa7k',
    appId: '1:117621637260:web:4d744dd2bcf08a9f8bfba9',
    messagingSenderId: '117621637260',
    projectId: 'diplomgrinenko',
    authDomain: 'diplomgrinenko.firebaseapp.com',
    storageBucket: 'diplomgrinenko.firebasestorage.app',
  );

}